### ISSUE TITLE
error - RPC error

### ISSUE THREAD

**Issue by pwjheu** [mui/mui-toolpad#2408]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. yarn create toolpad-app my-toolpad-app
2. yarn dev
3. error - RPC error on the terminal

### Current behavior 😯

PS C:\Users\Desktop\toolpad\my-toolpad-app> npm run dev
> my-toolpad-app@0.1.0 dev
> toolpad dev

info  - starting Toolpad application in dev mode...
info  - loaded env file "C:\Users\Desktop\toolpad\my-toolpad-app\.env" with keys 
ready - built functions.ts: 0 error(s), 0 warning(s)
ready - toolpad project C:\Users\Desktop\toolpad\my-toolpad-app ready on http://localhost:3000
(node:15272) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

error - RPC error
  TypeError: Cannot read properties of undefined (reading 'statusCode')
      at packageJson (C:\Users\Desktop\toolpad\my-toolpad-app\node_modules\node_modules\package-json\index.js:71:22)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at latestVersion (C:\Users\Desktop\toolpad\my-toolpad-app\node_modules\node_modules\latest-version\index.js:4:20)
      at async Promise.all (index 0)
      at checkVersion (C:\Users\Desktop\toolpad\my-toolpad-app\node_modules\@mui\toolpad\src\server\versionInfo.ts:43:36)
      at <anonymous> (C:\Users\Desktop\toolpad\my-toolpad-app\node_modules\@mui\toolpad\src\server\rpc.ts:82:21)

### Your environment 🌎

"@mui/toolpad": "^0.1.21"

**Comment by Janpot** [comment]
@pwjheu Would you mind checking which version of `package-json` is installed? e.g. what's the output of

```
yarn list package-json  
```

The issue we see here should've been fixed in the latest version https://github.com/sindresorhus/package-json/commit/80fb1fb397b3e88808b0bed39228621dc2778e93?diff=unified#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R71
