### ISSUE TITLE
Updating Toolpad breaks the app in https://github.com/mui/mui-private/tree/master/tools-private

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-toolpad#2934]
### Steps to reproduce 🕹

Steps:

1. Go to https://github.com/mui/mui-private/tree/master/tools-private
1. Update Toolpad from 0.1.24 to 0.1.38
2. See how http://localhost:3000/_toolpad/app/pages/f303n5n is broken
 - The date displayed is wrong

<img src="https://github.com/mui/mui-toolpad/assets/3165635/d89da443-d26c-44bd-b567-265ee1e9d48e" width="349">

 - Queries can't be added anymore, on a new page, it shows 500

<img src="https://github.com/mui/mui-toolpad/assets/3165635/ac54f12f-ee45-4ae2-aa29-c070ed61bbe5" width="">

**Comment by Janpot** [comment]
* The date object was introduced in 0.1.28 => `Date` objects aren't transferred from the server to the client. Looks like right now it can only transfer JSON.
* The 500 was introduced in 0.1.34: Running with `NODE_OPTIONS=--enable-source-maps` to get proper stack traces gives me:

    ```
    Error: Detected property constructor. This is a prototype pollution risk, please remove it from your object.
        at <anonymous> (/Users/janpotoms/Projects/mui-private/tools-private/node_modules/node_modules/superjson/src/plainer.ts:224:13)
        at <anonymous> (/Users/janpotoms/Projects/mui-private/tools-private/node_modules/node_modules/superjson/src/util.ts:45:52)
        at Array.forEach (<anonymous>)
        at forEach (/Users/janpotoms/Projects/mui-private/tools-private/node_modules/node_modules/superjson/src/util.ts:45:26)
        at walker (/Users/janpotoms/Projects/mui-private/tools-private/node_modules/node_modules/superjson/src/plainer.ts:218:3)
        at <anonymous> (/Users/janpotoms/Projects/mui-private/tools-private/node_modules/node_modules/superjson/src/plainer.ts:229:29)
        at <anonymous> (/Users/janpotoms/Projects/mui-private/tools-private/node_modules/node_modules/superjson/src/util.ts:45:52)
        at Array.forEach (<anonymous>)
        at forEach (/Users/janpotoms/Projects/mui-private/tools-private/node_modules/node_modules/superjson/src/util.ts:45:26)
        at walker (/Users/janpotoms/Projects/mui-private/tools-private/node_modules/node_modules/superjson/src/plainer.ts:218:3)
    ```
    Looks to be around the same area, in serialization/deserialization.

Will investigate further on Monday

**Comment by Janpot** [comment]
Ok, for the 500 we are having trouble transferring the typescript interface that describes the MySQL result. it contains a "constructor" property.

I don't immediately have a way to fix this besides reverting the update or writing our own smart serialization logic. I'm opening some issues in the hope thatw e can fix this without dropping a serialization library:

* https://github.com/Rich-Harris/devalue/issues/71
* https://github.com/blitz-js/superjson/issues/279

**Comment by Janpot** [comment]
Fixes in:
- https://github.com/mui/mui-toolpad/pull/2941
- https://github.com/mui/mui-toolpad/pull/2942
